# Generated by Django 3.2 on 2021-04-09 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_content', models.TextField()),
                ('mb_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mb_isShow', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'message_board',
            },
        ),
    ]
