# Generated by Django 3.2 on 2021-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='mb_isShow',
            field=models.BooleanField(default=True),
        ),
    ]
